dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - rust: stable
      env: RUSTFLAGS="--cfg finchers_deny_warnings"
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
      before_script:
        - rustup component add rustfmt-preview
        - cargo install cargo-update || true
        - cargo install cargo-kcov || true
        - cargo install-update -a
        - export CARGO_INCREMENTAL=0
      script:
        - cargo update
        - cargo test
        - cargo fmt -- --check
        - if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-}" = release-* ]]; then cargo publish --dry-run; fi
      after_success:
        - unset RUSTFLAGS
        - cargo kcov --print-install-kcov-sh | sh
        - cargo kcov -v --coveralls

    - rust: beta
      env: RUSTFLAGS="--cfg finchers_deny_warnings"
      script:
        - cargo update
        - cargo test

    - rust: nightly
      script:
        - cargo update
        - cargo test

    - rust: stable
      env: DEPLOY_API_DOC
      before_script:
      script:
        - rm -rf target/doc
        - cargo update
        - cargo doc --no-deps -p tungstenite
        - cargo doc --no-deps --all-features
        - rm -f target/doc/.lock
        - echo '<meta http-equiv="refresh" content="0;URL=finchers_tungstenite/index.html">' > target/doc/index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers-tungstenite
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
