(function() {var implementors = {};
implementors["finchers_tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"finchers_tungstenite/struct.WsEndpoint.html\" title=\"struct finchers_tungstenite::WsEndpoint\">WsEndpoint</a>",synthetic:false,types:["finchers_tungstenite::imp::WsEndpoint"]},];
implementors["tungstenite"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.OpCode.html\" title=\"enum tungstenite::protocol::frame::coding::OpCode\">OpCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::OpCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.Data.html\" title=\"enum tungstenite::protocol::frame::coding::Data\">Data</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::Data"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.Control.html\" title=\"enum tungstenite::protocol::frame::coding::Control\">Control</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::Control"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/frame/coding/enum.CloseCode.html\" title=\"enum tungstenite::protocol::frame::coding::CloseCode\">CloseCode</a>",synthetic:false,types:["tungstenite::protocol::frame::coding::CloseCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/protocol/enum.Role.html\" title=\"enum tungstenite::protocol::Role\">Role</a>",synthetic:false,types:["tungstenite::protocol::Role"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tungstenite/protocol/struct.WebSocketConfig.html\" title=\"struct tungstenite::protocol::WebSocketConfig\">WebSocketConfig</a>",synthetic:false,types:["tungstenite::protocol::WebSocketConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tungstenite/handshake/server/struct.NoCallback.html\" title=\"struct tungstenite::handshake::server::NoCallback\">NoCallback</a>",synthetic:false,types:["tungstenite::handshake::server::NoCallback"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tungstenite/stream/enum.Mode.html\" title=\"enum tungstenite::stream::Mode\">Mode</a>",synthetic:false,types:["tungstenite::stream::Mode"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
